/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADP.view;

import ADP.controller.ControllerBuscaChamados;
import ADP.controller.ControllerBuscaEquipamentos;
import ADP.controller.ControllerCadChamados;
import ADP.controller.ControllerCadEquipamento;
import javax.swing.JDesktopPane;

/**
 *
 * @author lucas
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpImg = new javax.swing.JDesktopPane();
        btnEqp = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnRegistroChamados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEqp.setText("Equipamento");
        btnEqp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqpActionPerformed(evt);
            }
        });

        jButton2.setText("Chamados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnInventario.setText("Inventário");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnRegistroChamados.setText("Registro de chamados");
        btnRegistroChamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroChamadosActionPerformed(evt);
            }
        });

        jdpImg.setLayer(btnEqp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpImg.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpImg.setLayer(btnInventario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpImg.setLayer(btnRegistroChamados, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpImgLayout = new javax.swing.GroupLayout(jdpImg);
        jdpImg.setLayout(jdpImgLayout);
        jdpImgLayout.setHorizontalGroup(
            jdpImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpImgLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jdpImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEqp, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                .addGroup(jdpImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistroChamados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(193, 193, 193))
        );
        jdpImgLayout.setVerticalGroup(
            jdpImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpImgLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(jdpImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEqp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(jdpImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpImg)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jdpImg)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEqpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqpActionPerformed
        Registro r = new Registro();
        ControllerCadEquipamento controllerCadEquipamento = new ControllerCadEquipamento(r);
        jdpImg.add(r);
        r.menu = this;
        r.setVisible(true);
    }//GEN-LAST:event_btnEqpActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        Inventário i = new Inventário();
        ControllerBuscaEquipamentos busca = new ControllerBuscaEquipamentos(i);
        
        jdpImg.add(i);
        i.menu =this;
        i.setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Chamados c = new Chamados();
        ControllerBuscaChamados cCad = new ControllerBuscaChamados(c);
        jdpImg.add(c);
        c.menu = this;
        c.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRegistroChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroChamadosActionPerformed
        RegistroChamados rc = new RegistroChamados();
        ControllerCadChamados controller = new ControllerCadChamados(rc);
        jdpImg.add(rc);
        rc.menu = this;
        rc.setVisible(true);
    }//GEN-LAST:event_btnRegistroChamadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
        public static JDesktopPane getPane() {
        return jdpImg;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEqp;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnRegistroChamados;
    private javax.swing.JButton jButton2;
    private static javax.swing.JDesktopPane jdpImg;
    // End of variables declaration//GEN-END:variables
}
